# build
custom_build(
    # name of container
    ref = 'dispatcher-service',
    # command to build the container
    command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
    # files to watch
    deps = ['build.gradle', 'src']
)

# deploy
k8s_yaml(['k8s/deployment.yml', 'k8s/service.yml'])

# manage
k8s_resource('dispatcher-service', port_forwards = ['9003'])
