spring:
  application:
    name: orders-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/orders_service_db
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  # flyway doesn't support reactive jdbc
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/orders_service_db
server:
  port: 9100
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

