spring:
  application:
    name: orders-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # in prod need to enable
      retry:
        max-attempts: 3
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/orders_service_db
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  # flyway doesn't support reactive jdbc
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/orders_service_db
server:
  port: 9100
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
cnative:
  catalog-service-uri: "http://localhost:9001"
