spring:
  application:
    name: orders-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/cnative}
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  cloud:
    function:
      definition: orderDispatched
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}
        acceptOrder-out-0:
          destination: order-accepted
      rabbit:
        bindings:
          acceptOrder-out-0:
            producer:
              transacted: true
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # in prod need to enable
      retry:
        max-attempts: 3
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/orders_service_db
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  # flyway doesn't support reactive jdbc
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/orders_service_db
server:
  port: 9100
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
management:
  endpoints:
    web:
      exposure:
        include: refresh
cnative:
  catalog-service-uri: "http://localhost:9001"
