include('../../../../config-service/Tiltfile')
include('../../../../catalogservice/Tiltfile')
include('../../../../orders-service/Tiltfile')
include('../../../../edge-service/Tiltfile')
include('../../../../dispatcher-service/Tiltfile')

update_settings(max_parallel_updates=1)
