spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # in prod need to enable
      retry:
        max-attempts: 3
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/catalog_service_db
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 2000
server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: refresh
polar:
  greeting: Welcome to local book Catalog
