services:
  catalog-service:
    image: catalog-service
    container_name: catalog-service
    ports:
      - "9001:9001"
      - "5005:5005"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-service-db:5432/catalog_service_db
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
    depends_on:
      - catalog-service-db
      - config-service
  config-service:
    image: config-service
    container_name: config-service
    ports:
      - "8888:8888"
      - "5008:5005"
    environment:
      - BPL_JVM_THREAD_COUNT=10
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
  catalog-service-db:
    image: postgres:17.4
    container_name: catalog-service-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog_service_db
    volumes:
      - "./AAA_build/dv-catalog-service-db:/var/lib/postgresql/data"

