services:
  catalog-service:
    image: catalog-service
    container_name: catalog-service
    ports:
      - "9001:9001"
      - "5005:5005"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cnative-db:5432/catalog_service_db
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false
    depends_on:
      config-service:
        condition: service_started
      cnative-db:
        condition: service_started
  config-service: # no curl/wget on buildpack image so health check is TBD
    image: config-service
    container_name: config-service
    ports:
      - "8888:8888"
      - "5008:5005"
    environment:
      - BPL_JVM_THREAD_COUNT=10
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
  orders-service:
    image: orders-service
    container_name: orders-service
    ports:
      - "9100:9100"
      - "5006:5005"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - SPRING_R2DBC_URL=r2dbc:postgresql://cnative-db:5432/orders_service_db
      - SPRING_FLYWAY_URL=jdbc:postgresql://cnative-db:5432/orders_service_db
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false
      - CNATIVE_CATALOG_SERVICE_URI=http://catalog-service:9001
    depends_on:
      config-service:
        condition: service_started
      cnative-db:
        condition: service_started
  cnative-db:
    image: postgres:17.4
    container_name: cnative-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./AAA_build/db-volume:/var/lib/postgresql/data"

