# build
custom_build(
    # name of container
    ref = 'edge-service',
    # command to build the container
    command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
    # files to watch
    deps = ['build.gradle', 'src']
)

# deploy
k8s_yaml(['k8s/deployment.yml', 'k8s/service.yml', 'k8s/ingress.yml'])

# manage
k8s_resource('edge-service', port_forwards = ['9000'])
