GET http://localhost:9001

### send refresh event so data gets updated
POST http://localhost:9001/actuator/refresh


###
POST http://localhost:9001/books
Content-Type: application/json

{
    "isbn": "1234567890",
    "title": "Sample Book Title",
    "author": "Sample Author",
    "price": 19.99
}

###

GET http://localhost:9001/books
Content-Type: application/json
