spring:
  application:
    name: config-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amantuladhar/cloud-native-spring-java
          default-label: main
          search-paths: config-store/**
          clone-on-start: true
          timeout: 5
          force-pull: true
server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
